version: "3.7"

services:
    {{SERVICE.PROXY_CA_FILE_ACCESS.NAME}}:
      image: sebp/lighttpd
      container_name: {{SERVICE.PROXY_CA_FILE_ACCESS.NAME}}
      hostname: lighttpd.{{SERVER.DOMAIN}}
      restart: always
      ports:
        - {{SERVICE.PROXY_CA_FILE_ACCESS.PORTS.PORT_EXPOSED}}:80
      networks:
        - {{SERVICE.NETWORK.NAME}}
      volumes:
        - {{SERVER.SERVER_HOME}}/Server/Squid/Cert:/var/www/localhost/htdocs

    {{SERVICE.SQUID.NAME}}:
      build:
        context: .
        args:
          - PROXY_PORT={{SERVICE.SQUID.PORTS.CACHING_PORT}}
          - PROXY_DOMAIN={{SERVER.DOMAIN}}
          - PROXY_COUNTRY={{SERVER.INFO.COUNTRY}}
          - PROXY_PROVINCE={{SERVER.INFO.PROVINCE}}
          - PROXY_CITY={{SERVER.INFO.CITY}}
          - PROXY_DEPARTMENT={{SERVER.INFO.DEPARTMENT}}
          - PROXY_USER={{SERVICE.SQUID.CREDENTIALS.USERNAME}}
          - PROXY_USER_PASSWORD={{SERVICE.SQUID.CREDENTIALS.PASSWORD}}
          - PROXY_CA_FILE={{SERVICE.PROXY.PROXY_CA_FILE}}
      container_name: {{SERVICE.SQUID.NAME}}
      hostname: squid.{{SERVER.DOMAIN}}
      restart: always
      ports:
        - {{SERVICE.SQUID.PORTS.CACHING_PORT}}:{{SERVICE.SQUID.PORTS.CACHING_PORT}}
      networks:
        - {{SERVICE.NETWORK.NAME}}
      volumes:
        - {{SERVER.SERVER_HOME}}/Server/Squid/Log:/var/log/squid
        - {{SERVER.SERVER_HOME}}/Server/Squid/Cache:/var/cache/squid
        - {{SERVER.SERVER_HOME}}/Server/Squid/Cert:/etc/squid/ssl_cert
        - {{SERVER.SERVER_HOME}}/Server/Squid/Users:/etc/squid/passwords

networks:
    {{SERVICE.NETWORK.NAME}}:
      external: true



